github workflows: fix role name

diff --git a/.github/workflows/default-bare.yml b/.github/workflows/default-bare.yml
--- a/.github/workflows/default-bare.yml
+++ b/.github/workflows/default-bare.yml
@@ -21,7 +21,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
         with:
-          path: juju4.upgrade-pkgs
+          path: juju4.upgrade_pkgs
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
@@ -37,7 +37,7 @@ jobs:
           ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
           echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
           ansible --version
-          cd $GITHUB_WORKSPACE/juju4.upgrade-pkgs
+          cd $GITHUB_WORKSPACE/juju4.upgrade_pkgs
           [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
           { echo '[defaults]'; echo 'callback_whitelist = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
       - name: Environment
@@ -51,13 +51,13 @@ jobs:
           systemctl status --all --no-pager || true
       - name: run test
         run: |
-          cd $GITHUB_WORKSPACE/juju4.upgrade-pkgs && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml
+          cd $GITHUB_WORKSPACE/juju4.upgrade_pkgs && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
       - name: idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/juju4.upgrade-pkgs && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)
+          cd $GITHUB_WORKSPACE/juju4.upgrade_pkgs && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)
       - name: On failure
         run: |
           systemctl -l --no-pager status
@@ -66,6 +66,5 @@ jobs:
         run: |
           systemd-analyze security || true
           systemctl --failed || true
-          systemctl status upgrade-pkgs || true
         if: ${{ always() }}
         continue-on-error: true
