ci: add macos, use env var ANSIBLE_ROLE

diff --git a/.github/workflows/default-bare.yml b/.github/workflows/default-bare.yml
--- a/.github/workflows/default-bare.yml
+++ b/.github/workflows/default-bare.yml
@@ -14,25 +14,39 @@ jobs:
   build:
     permissions:
       contents: read
-    runs-on: ${{ matrix.os }}
+    runs-on: ${{ matrix.distribution }}-${{ matrix.version }}
+    continue-on-error: ${{ matrix.experimental }}
     strategy:
       fail-fast: false
       max-parallel: 4
       matrix:
-        os: [ubuntu-latest, ubuntu-20.04]
+        include:
+          - distribution: ubuntu
+            version: '22.04'
+            experimental: false
+          - distribution: ubuntu
+            version: '20.04'
+            experimental: false
+          - distribution: macos
+            version: 12
+            experimental: true
     env:
       ANSIBLE_CALLBACKS_ENABLED: profile_tasks
+      ANSIBLE_ROLE: juju4.upgrade_pkgs
 
     steps:
       - uses: actions/checkout@v3
         with:
-          path: juju4.upgrade_pkgs
+          path: ${{ env.ANSIBLE_ROLE }}
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.x'
       - name: Install dependencies
         run: |
+          python3 --version
+          python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
+          python3 -c 'import ssl; ssl.PROTOCOL_TLSv1_2'
           python3 -m pip install --upgrade pip
           pip3 install ansible-lint flake8 yamllint
           which ansible
@@ -42,34 +56,42 @@ jobs:
           ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
           echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
           ansible --version
-          cd $GITHUB_WORKSPACE/juju4.upgrade_pkgs
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
           [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
           { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
       - name: Environment
         run: |
           pwd
           env
-          find -ls
+          find . -ls
       - name: Before script - systemctl
         run: |
           systemd-analyze security || true
           systemctl status --all --no-pager || true
+        if: matrix.distribution != 'macos'
       - name: run test
         run: |
-          cd $GITHUB_WORKSPACE/juju4.upgrade_pkgs && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
       - name: idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/juju4.upgrade_pkgs && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)
       - name: On failure
         run: |
           systemctl -l --no-pager status
-        if: env.WORKFLOW_CONCLUSION == 'failure'  # notify only if failure
+        if: matrix.distribution != 'macos' and env.WORKFLOW_CONCLUSION == 'failure'  # notify only if failure
       - name: After script - systemctl
         run: |
           systemd-analyze security || true
           systemctl --failed || true
         if: ${{ always() }}
+        continue-on-error: true
+      - name: After script - macos
+        run: |
+          set -x
+          port outdated || true
+          brew outdated || true
+        if: matrix.distribution == 'macos' and ${{ always() }}
         continue-on-error: true
